#!/usr/bin/env python3
"""Emit a C header of fixture byte arrays for the firmware protocol test.

Usage: python3 tools/fixtures_to_c.py [output_path]

Default output is build/audio_companion_fixtures.h. The firmware tree checks in
a generated copy at PebbleOS/tests/fw/services/audio_companion_fixtures.h;
regenerate and copy it whenever fixtures change.
"""

import json
import sys
from pathlib import Path

FIXTURES_DIR = Path(__file__).resolve().parent.parent / "spec" / "fixtures"

EXPECT_ENUM = {"parse": "FixtureExpectParse", "reject": "FixtureExpectReject",
               "ignore": "FixtureExpectIgnore"}
CHANNEL_ENUM = {"info": "FixtureChannelInfo", "control_in": "FixtureChannelControlIn",
                "control_out": "FixtureChannelControlOut", "data": "FixtureChannelData"}


def main():
    out_path = Path(sys.argv[1]) if len(sys.argv) > 1 else (
        Path(__file__).resolve().parent.parent / "build" / "audio_companion_fixtures.h")
    out_path.parent.mkdir(parents=True, exist_ok=True)

    entries = []
    for json_path in sorted(FIXTURES_DIR.glob("*.json")):
        if json_path.name.startswith("speex_"):
            # Codec fixtures (real encoded Speex), not protocol-message fixtures; the firmware
            # locks them in test_audio_companion_speex.c instead of the protocol table.
            continue
        meta = json.loads(json_path.read_text())
        bin_path = json_path.with_suffix(".bin")
        data = bin_path.read_bytes()
        entries.append((meta["name"], meta["channel"], meta["expect"], data,
                        meta.get("description", "")))

    lines = [
        "// GENERATED FILE - DO NOT EDIT",
        "// Generated by pebble-audio-companion/tools/fixtures_to_c.py from spec/fixtures/.",
        "// Regenerate with: python3 tools/fixtures_to_c.py <this file>",
        "",
        "#pragma once",
        "",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        "typedef enum {",
        "  FixtureExpectParse,",
        "  FixtureExpectReject,",
        "  FixtureExpectIgnore,",
        "} FixtureExpect;",
        "",
        "typedef enum {",
        "  FixtureChannelInfo,",
        "  FixtureChannelControlIn,",
        "  FixtureChannelControlOut,",
        "  FixtureChannelData,",
        "} FixtureChannel;",
        "",
        "typedef struct {",
        "  const char *name;",
        "  FixtureChannel channel;",
        "  FixtureExpect expect;",
        "  const uint8_t *data;",
        "  size_t length;",
        "} ProtocolFixture;",
        "",
    ]

    for name, _channel, _expect, data, description in entries:
        if description:
            lines.append(f"// {description}")
        if data:
            byte_lines = []
            for i in range(0, len(data), 12):
                chunk = ", ".join(f"0x{b:02x}" for b in data[i:i + 12])
                byte_lines.append(f"  {chunk},")
            lines.append(f"static const uint8_t s_fx_{name}[] = {{")
            lines.extend(byte_lines)
            lines.append("};")
        else:
            lines.append(f"static const uint8_t s_fx_{name}[] = {{ 0 }};  // empty fixture")
        lines.append("")

    lines.append("static const ProtocolFixture s_protocol_fixtures[] = {")
    for name, channel, expect, data, _description in entries:
        length = len(data)
        lines.append(
            f"  {{ \"{name}\", {CHANNEL_ENUM[channel]}, {EXPECT_ENUM[expect]}, "
            f"s_fx_{name}, {length} }},")
    lines.append("};")
    lines.append("")
    lines.append(
        "#define PROTOCOL_FIXTURE_COUNT (sizeof(s_protocol_fixtures) / "
        "sizeof(s_protocol_fixtures[0]))")
    lines.append("")

    out_path.write_text("\n".join(lines))
    print(f"wrote {len(entries)} fixtures to {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
